export const REQUEST_ROUTES = 'REQUEST_ROUTES';
export const RECEIVE_ROUTES = 'RECEIVE_ROUTES';
export const RECEIVE_ROUTES_ERROR = 'RECEIVE_ROUTES_ERROR';
export const REQUEST_SCHEDULES = 'REQUEST_SCHEDULES';
export const RECEIVE_SCHEDULES = 'RECEIVE_SCHEDULES';
export const RECEIVE_SCHEDULES_ERROR = 'RECEIVE_SCHEDULES_ERROR';
export const SET_ROUTE = 'SET_ROUTE';
export const SWITCH_DESTINATION = 'SWITCH_DESTINATION';

export default {
  REQUEST_ROUTES,
  RECEIVE_ROUTES,
  RECEIVE_ROUTES_ERROR,
  REQUEST_SCHEDULES,
  RECEIVE_SCHEDULES,
  RECEIVE_SCHEDULES_ERROR,
  SET_ROUTE,
  SWITCH_DESTINATION,
};
