export const REQUEST_ROUTES = 'REQUEST_ROUTES';
export const RECEIVE_ROUTES = 'RECEIVE_ROUTES';
export const RECEIVE_ROUTES_ERROR = 'RECEIVE_ROUTES_ERROR';

export default {
  REQUEST_ROUTES,
  RECEIVE_ROUTES,
  RECEIVE_ROUTES_ERROR,
}
